PMM-11488 PGSM 2.0 doc correction/changes.
percona/pmm-doc pull request #1032
Opened 2023-03-24 08:55 UTC by JiriCtvrtka

2023-03-24 09:01 UTC, JiriCtvrtka commented
@PeterZaitsev Hi Peter, based on your email I addressed several changes. Please take a look if its more clear, or feel free to add your suggestions. Thank you.

2023-03-27 06:52 UTC, rasika-chivate requested changes

2023-03-27 06:52 UTC, rasika-chivate commented on docs/get-started/query-analytics.md
> +    where USERNAME should be replaced by your user.
```suggestion
    where `USERNAME` should be replaced by the user.
```

2023-03-27 06:52 UTC, rasika-chivate commented on docs/release-notes/2.36.0.md
> +    PMM 2.36 together with PGSM 2.0 now supports PG 13, 14 and 15. Support for older versions (PG 11 and 12) will be introduced in PMM 2.37.
```suggestion
    PMM 2.36 and PGSM 2.0 now support PG 13, 14, and 15. Support for older versions (PG 11 and 12) will be introduced in PMM 2.37.
```

2023-04-05 11:41 UTC, rasika-chivate approved these changes

2023-04-06 10:11 UTC, merged