PMM-11438 env var with disable build-in
percona/pmm-doc pull request #1035
Opened 2023-03-27 13:38 UTC by rishat-ishbulatov

[PMM-10913](https://jira.percona.com/browse/PMM-11438)

Build: [PMM-10913](https://github.com/Percona-Lab/pmm-submodules/pull/2965)

2023-03-31 09:26 UTC, denisok requested changes
I think it should be at the end of the table and also needs to be added here: https://pmm-doc-pr-1035.onrender.com/setting-up/server/docker.html#environment-variables

2023-03-31 10:20 UTC, denisok approved these changes

2023-04-04 16:13 UTC, rasika-chivate requested changes

2023-04-04 16:13 UTC, rasika-chivate commented on docs/details/postgresql.md
> +| `PMM_DISABLE_BUILTIN_POSTGRES`       |           | Environment variable to disable built-in PMM-Server database.
```suggestion
| `PMM_DISABLE_BUILTIN_POSTGRES`       |           | Environment variable to disable built-in PMM server database.
```

2023-04-05 05:26 UTC, rasika-chivate approved these changes

2023-04-05 05:26 UTC, merged