PMM-11951-documentation-for-external-postgres
percona/pmm-doc pull request #1049
Opened 2023-04-06 16:22 UTC by rishat-ishbulatov

[Ticket](https://jira.percona.com/browse/PMM-11951)
[PR](https://github.com/percona/pmm/pull/1521)[
Build](https://github.com/Percona-Lab/pmm-submodules/pull/3185)

2023-04-06 16:35 UTC, Nailya requested changes

2023-04-06 16:35 UTC, Nailya commented on docs/details/postgresql.md
>  2. Deploy Percona Server with certificates under read-only permissions and Grafana user and Grafana group.
change to PMM server

2023-04-06 16:51 UTC, rishat-ishbulatov commented on docs/details/postgresql.md
>  2. Deploy Percona Server with certificates under read-only permissions and Grafana user and Grafana group.
done

2023-04-07 05:26 UTC, denisok approved these changes

2023-04-07 07:42 UTC, Nailya approved these changes

2023-04-10 20:45 UTC, rasika-chivate approved these changes

2023-04-12 09:13 UTC, denisok approved these changes

2023-04-12 09:24 UTC, BupycHuk approved these changes

2023-04-12 09:34 UTC, rasika-chivate approved these changes

2023-04-12 09:34 UTC, merged