PMM release 2.38.0
percona/pmm-doc pull request #1081
Opened 2023-05-24 13:04 UTC by rasika-chivate

1. Documentation tasks for PMM 2.38.0
2. Config changes for PMM 2.38.0

2023-06-28 08:07 UTC, rnovikovP requested changes
The inventory page need to me moved out of the Dashboards section

see https://perconacorp.slack.com/archives/C03FB1CAZH9/p1687877418313419

2023-06-29 14:14 UTC, rnovikovP commented on docs/release-notes/2.38.0.md
> +| **Release date:** | Jun 29, 2023                                                                                    |
```suggestion
| **Release date:** | Jul 3, 2023                                                                                    |
```

2023-06-29 15:04 UTC, idoqo commented on docs/release-notes/2.38.0.md
> +#### Better folder management for enhanced PMB compatibility
```suggestion
#### Better folder management for enhanced PBM compatibility 
```

2023-07-03 10:44 UTC, rnovikovP approved these changes

2023-07-03 10:48 UTC, BupycHuk approved these changes

2023-07-03 15:06 UTC, merged