first changes
percona/pmm-doc pull request #1088
Opened 2023-05-31 07:05 UTC by catalinaadam

2023-05-31 09:31 UTC, PavelKhripkov requested changes

2023-06-07 10:23 UTC, fabio-silva approved these changes

2023-06-07 11:16 UTC, artemgavrilov approved these changes

2023-06-07 11:16 UTC, artemgavrilov commented on docs/get-started/backup/create_PITR_mongo.md
> +    Auto-retry mode enables you to select up to ten retries and an interval of up to eight hours between retries.<a id="folder-field"></a>
This `<a id="folder-field"></a>` looks like some leftover

2023-06-07 11:16 UTC, artemgavrilov commented on docs/get-started/backup/create_mongo_on_demand.md
> +9. Expand **Advanced Settings** to specify the settings for retrying the backup in case of any issues. You can either let PMM retry the backup again (**Auto**), or do it again yourself (**Manual**).
Same `<a id="folder-field"></a>`

2023-06-07 11:16 UTC, artemgavrilov commented on docs/get-started/backup/create_mysql_backup.md
> +    - **Retention**: this option is only available for Snapshot backups stored on S3-compatible object storage. If you want to keep an unlimited number of backup artifacts, type `0`.<a id="folder-fie
Same `<a id="folder-field"></a>`

2023-06-07 11:19 UTC, merged