manual upgrade clarification
percona/pmm-doc pull request #1112
Opened 2023-07-07 13:13 UTC by catalinaadam

2023-07-07 13:30 UTC, rnovikovP commented
we see https://perconacorp.slack.com/archives/C03FB1CAZH9/p1688715789544119 that in some cases people reading our RN and blog as "you can't now use UI to get updates" so looking for some clarification here, to make it clear what is limited exactly.

2023-08-02 09:23 UTC, rnovikovP commented
I think we need to rewrite the full section about the upgrade: 
Start from :  

- People using docker upgrade - will be fine 
- Update button users  - can continue using the button but then they'll not get the base OS updated or execute manual upgrade based on their distribution: docker , ami/ovf  - links to specific instructions how to upgrade not using  upgrade button

2023-11-15 19:07 UTC, BupycHuk approved these changes

2023-11-15 19:07 UTC, BupycHuk commented on docs/release-notes/2.38.0.md
> +AMI, OVF users and Docker users who want to upgrade PMM via the **Upggrade Now** option on the Home Dashboard will have to wait a little longer for an automated migration path from Centos 7 to Oracle
```suggestion
AMI, OVF users and Docker users who want to upgrade PMM via the **Upgrade Now** option on the Home Dashboard will have to wait a little longer for an automated migration path from Centos 7 to Oracle Linux 9.
```

2023-11-16 12:20 UTC, rnovikovP requested changes
https://github.com/percona/pmm-doc/pull/1112#issuecomment-1661853754

2024-07-02 08:44 UTC, closed without merging