PMM_Release_2.40.0
percona/pmm-doc pull request #1139
Opened 2023-08-28 04:47 UTC by rasika-chivate

All the documentation tickets for 2.40.0 should be merged in this branch. 

Also, update the following files:

1. index.md
2. mkdocs-base.yml
3. variables

2023-09-29 09:00 UTC, ademidoff requested changes
We have reverted this ultimately.

2023-09-29 09:00 UTC, ademidoff commented on docs/get-started/roles-and-permissions/lbac.md
> +    With PMM 2.40.0, we start enforcing the cluster label. If you choose not to provide it explicitly while adding a service to PMM for monitoring, PMM will automatically assign the value of the serv
```suggestion
```

2023-09-29 09:00 UTC, ademidoff commented on docs/get-started/roles-and-permissions/lbac.md
> +    ![!](../../_images/PMM_access_control_service_name_assigned_cluster.png)
```suggestion
```
Let's also remove the image!

2023-09-29 09:25 UTC, ademidoff commented
@rasika-chivate Should we remove the image as well?

2023-09-29 09:42 UTC, ademidoff approved these changes

2023-10-02 08:58 UTC, BupycHuk approved these changes

2023-10-05 11:48 UTC, merged