Adding note on performance_schema_max_digest_length
percona/pmm-doc pull request #1153
Opened 2023-09-27 14:14 UTC by nethalo

2023-11-22 22:39 UTC, nethalo commented on docs/setting-up/client/mysql.md
> +    When dealing with long queries, increasing the value of the variable [performance_schema_max_digest_length](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-system-variables.html#sysvar
But that is a pmm-admin config parameter and not a MySQL variable. I'd defer that to be added by the doc team

2023-11-22 22:44 UTC, BupycHuk requested changes

2023-11-22 22:44 UTC, BupycHuk commented on docs/setting-up/client/mysql.md
> +    When dealing with long queries, increasing the value of the variable [performance_schema_max_digest_length](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-system-variables.html#sysvar
than it won't be true in context of PMM. @rnovikovP PTAL ^

2023-11-23 11:19 UTC, rnovikovP commented on docs/setting-up/client/mysql.md
> +    When dealing with long queries, increasing the value of the variable [performance_schema_max_digest_length](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-system-variables.html#sysvar
As I understand, To have queries with full length it's 2 parameters need to be tuned: 
1) MySQL perf schema ^ 
2) PMM flag for the length 

If both of them are aligned - then the user will see the full query (most likely .. still can be a problem with veeeeryyyy long queries )

2023-11-26 21:01 UTC, nethalo commented on docs/setting-up/client/mysql.md
> +    When dealing with long queries, increasing the value of the variable [performance_schema_max_digest_length](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-system-variables.html#sysvar
This is a PR for a note explaining a Performance Schema modification. Please make another one for non-related information (non-mysql modification) @rnovikovP

2024-05-20 15:04 UTC, BupycHuk approved these changes

2024-05-20 15:04 UTC, merged