D baa s warning
percona/pmm-doc pull request #1165
Opened 2023-10-16 10:20 UTC by catalinaadam

2023-10-23 11:57 UTC, matejkubinec commented
Looks good to me.

Are the links to migration guide/everest final?

2023-10-23 11:59 UTC, matejkubinec approved these changes

2023-10-23 12:03 UTC, rnovikovP requested changes
Everest - http://per.co.na/pmm-to-everest 
guide - http://per.co.na/pmm-to-everest-guide 

We must use the short links here, not the destinations as the links are not final yet.

2023-10-25 11:46 UTC, matejkubinec approved these changes

2023-11-06 15:39 UTC, merged