PMM-12422-exporters-bind-push-mode
percona/pmm-doc pull request #1168
Opened 2023-10-18 06:23 UTC by rasika-chivate

For details see,

https://jira.percona.com/browse/PMM-12422

2023-10-18 09:07 UTC, rnovikovP requested changes
1) it's a little confusing to have different explanations for the same flag. is it really working differently based on agent or admin usage? 
2) "`0.0.0.0` address"  vs "127.0.0.1" explanation is very technical. Can we have a human-friendly one? To explain what this will cause for the user.

2023-11-15 17:15 UTC, BupycHuk commented on docs/details/commands/pmm-admin.md
> +: When enabled, the exporter created for that service will use the `0.0.0.0` address.
there are good explanation in RN

2023-11-22 10:41 UTC, BupycHuk approved these changes

2023-11-22 10:50 UTC, idoqo commented on docs/details/commands/pmm-admin.md
> +`--expose-exporter-address` (This flag is availble starting with PMM 2.41.0.)
```suggestion
`--expose-exporter` (This flag is availble starting with PMM 2.41.0.)
```

We figured `--expose-exporter-address` felt too long, so we went with `--expose-exporter`

2023-11-22 10:50 UTC, idoqo commented on docs/details/commands/pmm-admin.md
> +: If you enable this flag, any IP address on the local network and anywhere on the internet can access exporter endpoints. If the flag is disabled, exporter endpoints can be accessed only locally.
```suggestion
: If you enable this flag, any IP address on the local network and anywhere on the internet can access exporter endpoints. If the flag is disabled/not present, exporter endpoints can be accessed only locally. The flag is disabled by default
```

2023-11-22 10:50 UTC, idoqo commented on docs/details/commands/pmm-agent.md
> +| `--expose-exporter-address` (This flag is available starting with PMM 2.41.0.)| | If you enable this flag, any IP address on the local network and anywhere on the internet can access node exporter
```suggestion
| `--expose-exporter` (This flag is available starting with PMM 2.41.0.)| | If you enable this flag, any IP address on the local network and anywhere on the internet can access node exporter endpoints. If the flag is disabled, node exporter endpoints can be accessed only locally.
```

2023-11-23 10:36 UTC, rnovikovP approved these changes
LGTM, but with  @idoqo comment re default value

2023-11-24 08:07 UTC, idoqo approved these changes

2023-11-24 08:08 UTC, merged