RN_updates_2-40.1
percona/pmm-doc pull request #1170
Opened 2023-10-24 05:47 UTC by rasika-chivate

update the relese notes for PMM 2.40.1

2023-10-24 07:38 UTC, browseman requested changes

2023-10-24 07:38 UTC, browseman commented on docs/release-notes/2.40.1.md
> +        This step will cause any changes made to Grafana after upgrading to version 2.40.0 to be lost.
`This step will cause a loss of all changes made to Grafana after upgrading to version 2.40.0.`
Please consider this one, at least for me it "sound" better.

2023-10-24 07:38 UTC, browseman commented on docs/release-notes/2.40.1.md
> +    The steps below are only applicable to users who have upgraded to 2.40.0 and have been experiencing this problem.
`experiencing this problem. `
Could you please specify explicitly for which problems this fix is needed: PMM-12592 + PMM-12576 + PMM-12587

2023-10-24 08:00 UTC, rasika-chivate commented on docs/release-notes/2.40.1.md
> +    The steps below are only applicable to users who have upgraded to 2.40.0 and have been experiencing this problem.
Fixed.

2023-10-24 08:07 UTC, rnovikovP commented on docs/release-notes/2.40.1.md
> +- [PMM-12592](https://jira.percona.com/browse/PMM-12592) - After upgrading to PMM 2.40.0, changing the Admin user's password from the terminal was not functioning. The issue has been resolved now.
not sure this is needed. looks like typo

2023-10-24 08:14 UTC, Nailya approved these changes

2023-10-24 12:03 UTC, BupycHuk approved these changes

2023-10-24 12:03 UTC, BupycHuk commented on docs/release-notes/2.40.1.md
>  ## How to upgrade to PMM 2.40.1
I think it's better to rename this title as
```suggestion
## How to upgrade from 2.40.0 to PMM 2.40.1
```
to make it clear. Users might skip cautions below.

2023-10-25 11:15 UTC, rnovikovP approved these changes

2023-10-25 13:02 UTC, merged