Relelase Branch 2.41.1
percona/pmm-doc pull request #1188
Opened 2023-12-13 06:40 UTC by rasika-chivate

2024-01-04 10:11 UTC, rnovikovP commented on variables.yml
> +release_date: 2024-01-09
```suggestion
release_date: 2024-01-24
```

2024-01-25 13:05 UTC, rnovikovP approved these changes

2024-01-26 15:03 UTC, ondrejpatocka commented
Hi, I noticed there are old Jira issues links in RN on
https://pmm-doc-pr-1188.onrender.com/release-notes/2.41.1.html#improvements
Is it expected?

2024-01-29 10:20 UTC, rnovikovP commented on docs/release-notes/2.41.1.md
> +Explore and leverage this new metric to enhance your understanding of your sharded MongoDB setup.
```suggestion
This version is not yet used in any dashboard, but you can use it in your custom dashboards (you can use https://www.youtube.com/watch?v=vk1QBiMVzz4 and https://docs.percona.com/percona-monitoring-and-management/details/dashboards/dashboard-manage-dashboards.html )

Please share your feedback on our forum (forum.percona.com)
```

2024-01-29 10:35 UTC, rnovikovP commented on docs/release-notes/2.41.1.md
> +
```suggestion

### New Experimental MongoDB Instance Summary dashboard
We have introduced a new MongoDB Instance summary in this release that offers PMM users a simplified view of the most critical MongoDB metrics. You can locate it in the "Experimental" folder of your PMM installation. We request you to verify it against your MongoDB instance and share your feedback on our forum.

```

2024-01-29 11:23 UTC, sleto-it commented
Direct link to preview the changes, as the 2.41.1.md page is not currently linked in the release notes index:

https://pmm-release-branch-pr-1188.onrender.com/release-notes/2.41.1.html

2024-01-29 11:39 UTC, sleto-it commented
[PMM-12350](https://perconadev.atlassian.net/browse/PMM-12350) is not mentioned in the release notes - but I assume it was fixed as well?

2024-01-29 17:24 UTC, ondrejpatocka commented
Hi @rasika-chivate and @catalinaadam I'm checking latest RN for 2.41.1 on https://pmm-doc-pr-1188.onrender.com/release-notes/2.41.1.html
and there are bugs (and improvements) missing/not mentioned, compared to Jira tickets list below.
Is it intentional, or am I checking wrong source?

# Release notes - Percona Monitoring and Management - 2.41.1

### Improvement

[PMM-12390](https://perconadev.atlassian.net/browse/PMM-12390) MongoDB Backup / Service Name - Make the text search case insensitive

[PMM-12510](https://perconadev.atlassian.net/browse/PMM-12510) No support of MongoDB arbiters with Authorization enabled

[PMM-12712](https://perconadev.atlassian.net/browse/PMM-12712) Collect Data about Sharded collections in MongoDB 

[PMM-12750](https://perconadev.atlassian.net/browse/PMM-12750) \[Tech Preview\] Single dashboard with important MongoDB KPIs

[PMM-12846](https://perconadev.atlassian.net/browse/PMM-12846) Telemetry: data for the client node version 

[PMM-12866](https://perconadev.atlassian.net/browse/PMM-12866) K8s experimental dashboard update 

### Bug

[PMM-9407](https://perconadev.atlassian.net/browse/PMM-9407) PMM2-Client Debian doesn't include queries.yaml inside Postgresql Medium Resolution

[PMM-9825](https://perconadev.atlassian.net/browse/PMM-9825) QAN: Strange values in User Name filter with pg\_stat\_monitor

[PMM-12290](https://perconadev.atlassian.net/browse/PMM-12290) Comments are parsed by default for remotely added PostgreSQL and MySQL

[PMM-12350](https://perconadev.atlassian.net/browse/PMM-12350) Error in mongod\_exporter logs when pmm-agent is connected to mongos

[PMM-12425](https://perconadev.atlassian.net/browse/PMM-12425) QAN picking different date range will cause an error 

[PMM-12473](https://perconadev.atlassian.net/browse/PMM-12473) Unable to add external service with a query string in the metrics-path

[PMM-12621](https://perconadev.atlassian.net/browse/PMM-12621) Show all service types in anonymous mode

[PMM-12652](https://perconadev.atlassian.net/browse/PMM-12652) Issues upgrading to >=2.38.x with SELinux enabled

[PMM-12738](https://perconadev.atlassian.net/browse/PMM-12738) certificate.conf required, but not mentioned anywhere in helm charts

[PMM-12781](https://perconadev.atlassian.net/browse/PMM-12781) permission denied for function pg\_ls\_waldir

[PMM-12807](https://perconadev.atlassian.net/browse/PMM-12807) "Skip TLS certificate and hostname validation" flag isn't working.

[PMM-12815](https://perconadev.atlassian.net/browse/PMM-12815) pmm client fails to add mongoDB via socket

[PMM-12816](https://perconadev.atlassian.net/browse/PMM-12816) PMM Upgrade sporadically fails for 2.37.1 and 2.38.0 to 2.41.1

2024-01-30 10:28 UTC, catalinaadam commented
> Hi @rasika-chivate and @catalinaadam, I noticed there are old Jira issues links in RN on https://pmm-doc-pr-1188.onrender.com/release-notes/2.41.1.html#improvements Is it expected? For now the old->new Jira links redirect works, but will be disabled eventually.
@ondrejpatocka, for PXB 8.2 they got mapped automatically  and opened in Cloud Jira

2024-01-31 07:50 UTC, rnovikovP commented on docs/release-notes/2.41.1.md
> +
@catalinaadam  pls 👁️  this is for the [PMM-12750](https://perconadev.atlassian.net/browse/PMM-12750)

2024-01-31 07:53 UTC, rnovikovP commented on docs/release-notes/2.41.1.md
> +
```suggestion

[PMM-12750](https://perconadev.atlassian.net/browse/PMM-12750) [Dashboards] Tech Preview* of the new MongoDB Instance Summary

[PMM-12866](https://perconadev.atlassian.net/browse/PMM-12866) [Dashboards] update of K8s experimental dashboard (Tech Preview*)

```

2024-01-31 08:17 UTC, rnovikovP commented on docs/release-notes/2.41.1.md
> +
- [PMM-9407] (https://perconadev.atlassian.net/browse/PMM-9407): Fixed issue with executing Custom Queries for PostgreSQL on Debian due to the absence of queries.yaml within packages.
- [PMM-12290](https://perconadev.atlassian.net/browse/PMM-12290) [QAN] Fixed bugs with SQL comments parsed in queries when they were not intentionally enabled for remotely added PostgreSQL and MySQL.
- [PMM-12350](https://perconadev.atlassian.net/browse/PMM-12350) Fixed problem with mongod_exporter flood logs when connected to Mongos. 
- [PMM-12738](https://perconadev.atlassian.net/browse/PMM-12738) Fixed bug with inability to run PMM using Helm with customer certificates.  
- [PMM-12781](https://perconadev.atlassian.net/browse/PMM-12781) Fixed a permission error that flooded PostgreSQL logs by fixing the pg_ls_waldir function's execution permissions.

2024-01-31 08:18 UTC, rnovikovP requested changes

2024-01-31 11:54 UTC, sleto-it approved these changes
Approving from my side, as my feedback wrt PMM-12350 has been handled.

We still need to link page 2.41.1.md into the release note index, it seems.

2024-02-01 13:13 UTC, rnovikovP approved these changes

2024-02-01 19:31 UTC, merged