PMM 3.0.0 Alpha Rel Notes
percona/pmm-doc pull request #1221
Opened 2024-03-06 09:23 UTC by catalinaadam

2024-04-04 09:55 UTC, rnovikovP commented on docs/release-notes/3.0.0_Alpha.md
> +### Transition to Oracle Linux 9 completed
maybe shorten this section to just say - RHEL 7 is dead , so no EL 7 builds, everything on OL9 - as most secured and recent version of OS

2024-04-04 09:57 UTC, rnovikovP commented on docs/release-notes/3.0.0_Alpha.md
> +### Grafana upgraded to latest version
Let's move this section to the bottom of the highlights as this is inherited features 

(I'll additionally review them )

2024-04-04 09:58 UTC, rnovikovP commented on docs/release-notes/3.0.0_Alpha.md
> +## Finalized DBaaS migration to Percona Everest
let's add here about seamless integration from everest to PMM when you use pmm for monitoring (this  should be already in latest version of Everest )

2024-04-04 10:04 UTC, BupycHuk approved these changes

2024-04-04 10:04 UTC, BupycHuk commented on docs/release-notes/3.0.0_Alpha.md
> +PMM is now deployed inside containers within AMI and OVF instances. These containers operate in a rootless mode and are managed via Podman. This approach significantly increases security for a more r
and provides the same experience across different deployment types

2024-04-10 09:39 UTC, Nailya approved these changes

2024-05-06 10:03 UTC, ademidoff requested changes

2024-05-06 10:03 UTC, ademidoff commented on docs/release-notes/3.0.0_Alpha.md
> +- [PMM-8306](https://perconadev.atlassian.net/browse/PMM-8306): Deployed PMM inside rootless containers managed by Podman within AMI and OVF instances, enhancing security and providing a consistent e
```suggestion
- [PMM-8306](https://perconadev.atlassian.net/browse/PMM-8306): Deployed PMM as a rootless container managed by Podman within AMI and OVF instances, enhancing security and providing a consistent experience across different deployment types.
```

2024-05-06 10:03 UTC, ademidoff commented on docs/release-notes/3.0.0_Alpha.md
> +- [PMM-8306](https://perconadev.atlassian.net/browse/PMM-8306): Deployed PMM inside rootless containers managed by Podman within AMI and OVF instances, enhancing security and providing a consistent e
This seems to be more correct.

2024-05-07 11:09 UTC, matejkubinec commented on docs/release-notes/3.0.0_Alpha.md
> +We've made administration settings easier to manage by introducing a new **Administration** menu. This menu brings together all Grafana-related configurations and account management options that were
Just a note, the "Administration" menu (Merged "Configuratio" and "Server Admin") was introduced by Grafana.

2024-05-09 09:13 UTC, merged