Create advisors-details.md
percona/pmm-doc pull request #1223
Opened 2024-03-07 12:36 UTC by rnovikovP

2024-03-19 10:59 UTC, ademidoff requested changes

2024-03-19 10:59 UTC, ademidoff commented on docs/get-started/advisors-details.md
> +For simplicity, we also listening all Advisors and checks on this page:
```suggestion
For simplicity, we also listing all Advisors and checks on this page:
```

2024-03-19 10:59 UTC, ademidoff commented on docs/get-started/advisors-details.md
> +Every Advisor consists of the advisor checks inside.
```suggestion
Every Advisor consists of one or more Advisor checks. 
```

2024-03-19 10:59 UTC, ademidoff commented on docs/get-started/advisors-details.md
> +We have listed the checks and their details here for more detailed information.
```suggestion
We have listed the checks and their details here.
```

2024-03-19 13:39 UTC, catalinaadam commented on docs/get-started/advisors-details.md
> +| Generic Configuration | mysql\_config\_binlog\_row\_image | Please consider setting binlog\_row\_image=FULL. | Binlogs raw image is not set to FULL |
The Summary does not match the format of the other ones, which seems to be a Title format. Instead it kind of duplicates the description. Should it be "automatic\_sp\_privileges check"?

2024-03-19 14:25 UTC, catalinaadam commented on docs/get-started/advisors-details.md
> +| Generic Configuration | mysql\_config\_binlog\_row\_image | Please consider setting binlog\_row\_image=FULL. | Binlogs raw image is not set to FULL |
Checks whether binlogs are being rotated too frequently, which is not recommended except in very specific cases.
```suggestion
| Generic Configuration | mysql\_config\_binlog\_retention\_period | Binlogs should not be rotated too often, except very specific cases.| Binlogs Retention Check |
```

2024-03-19 14:49 UTC, catalinaadam commented on docs/get-started/advisors-details.md
> +| Replication Configuration| mysql\_config\_relay\_log\_purge | Identify if a replica node has relay-logs purge set. | Automatic relay log purging is off |
Is this description correct for this entry?

2024-03-22 11:58 UTC, BupycHuk approved these changes

2024-04-01 13:11 UTC, catalinaadam approved these changes

2024-04-01 13:39 UTC, ademidoff approved these changes

2024-04-01 13:39 UTC, merged