Updated migration steps
percona/pmm-doc pull request #1331
Opened 2024-11-13 16:59 UTC by catalinaadam

2024-11-15 08:28 UTC, Nailya requested changes

2024-11-15 08:28 UTC, Nailya commented on docs/pmm-upgrade/migrating_from_pmm_2.md
> +=== "For Docker Volume"
I'd rename it to something like "For those running PMM v2 with docker volumes" to clarify that these steps should be executed if PMM2 server is running using docker volume container

2024-11-15 08:28 UTC, Nailya commented on docs/pmm-upgrade/migrating_from_pmm_2.md
> +=== "For Data Container"
Same here. I'd rename it to something like "For those running PMM v2 with docker data containers" to clarify that these steps should be executed if PMM2 server is running using docker data-container

2024-11-15 15:21 UTC, ademidoff commented on docs/pmm-upgrade/migrating_from_pmm_2.md
> +    docker run -d --volumes-from pmm-server-data -p 80:8080 -p 443:8443 --name pmm-server --restart always percona/pmm-server:3
```suggestion
    docker run -d --volumes-from pmm-server-data -p 443:8443 --name pmm-server --restart always percona/pmm-server:3
```

2024-11-15 15:21 UTC, ademidoff commented on docs/pmm-upgrade/migrating_from_pmm_2.md
> +    docker run -d -v pmm-server-data:/srv -p 80:8080 -p 443:8443 --name pmm-server --restart always percona/pmm-server:3
```suggestion
    docker run -d -v pmm-server-data:/srv -p 443:8443 --name pmm-server --restart always percona/pmm-server:3
```

2024-11-19 11:47 UTC, BupycHuk approved these changes

2024-11-20 11:52 UTC, merged