PMM-7105 MariaDB workaround
percona/pmm-doc pull request #345
Opened 2021-01-05 06:58 UTC by PaulJacobs-percona

2021-01-07 12:24 UTC, BupycHuk requested changes
Forgot to add schema name

2021-01-07 12:24 UTC, BupycHuk commented on docs/setting-up/client/mysql.md
> +UPDATE setup_instruments SET ENABLED = 'YES', TIMED = 'YES'
```suggestion
UPDATE performance_schema.setup_instruments SET ENABLED = 'YES', TIMED = 'YES'
```

2021-01-07 12:24 UTC, BupycHuk commented on docs/setting-up/client/mysql.md
> + UPDATE setup_consumers SET ENABLED = 'YES'
```suggestion
 UPDATE performance_schema.setup_consumers SET ENABLED = 'YES'
```

2021-01-11 16:18 UTC, rnovikovP approved these changes

2021-01-11 16:34 UTC, BupycHuk approved these changes

2021-01-12 11:33 UTC, merged