Update configure.md
percona/pmm-doc pull request #463
Opened 2021-04-21 14:03 UTC by rnovikovP

Add Clafirication about "what happened if I'll enable and then disable feature "

2021-04-21 14:39 UTC, BupycHuk commented on docs/how-to/configure.md
> +If you'll disable the already enabled Microsoft Azure monitoring feature you will not be able to do discovery and add Azure instances using the native  UI from PMM. No date related to already added A
```suggestion
If you'll disable the already enabled Microsoft Azure monitoring feature you will not be able to do discovery and add Azure instances using the native  UI from PMM. Data related to already added Azure instances will not be deleted and already added instances will be monitored 
```

2021-04-22 06:05 UTC, PaulJacobs-percona commented on docs/how-to/configure.md
> +If you'll disable the already enabled Telemetry feature PMM will stop sending data and all feature where you can get some data from Percona will be not available to be enabled
```suggestion
>
> - Disabling telemetry prevents you from using features that require data from us.
```

2021-04-22 06:11 UTC, PaulJacobs-percona commented on docs/how-to/configure.md
> +If you'll disable the already enabled Check for Updates feature you will not be longer informed about new versions of PMM and might miss important features we'll ad in future
```suggestion
If you turn this off you will not know about important updates and features without watching our forum and release notes pages.
```

2021-04-22 06:11 UTC, PaulJacobs-percona commented on docs/how-to/configure.md
> +If you'll disable the already enabled Check for Updates feature you will not be longer informed about new versions of PMM and might miss important features we'll ad in future
But I'd rather omit this entirely, as our readers/users are smart and can figure it out for themselves.

2021-04-22 06:12 UTC, PaulJacobs-percona commented on docs/how-to/configure.md
> +If you'll disable the already enabled Security Threat Tool  feature you will not be able to see the Security alerts and Security Checks will not be executed on the system
As above, we are just stating the obvious. We are in danger of insulting the intelligence of our readers with such words.

2021-04-22 06:16 UTC, PaulJacobs-percona commented on docs/how-to/configure.md
> +If you'll disable the already enabled DBaaS feature you will not lose any of your K8s data or DB cluster. The only effect this will have is the DBaaS menu will disappear from the PMM
```suggestion
This setting only shows and hides DBaaS features. Your Kubernetes and DB clusters are unaffected.
```

2021-04-22 06:19 UTC, PaulJacobs-percona commented on docs/how-to/configure.md
> +If you'll disable the already enabled Integrated Alerting feature you will stop receiving the notifications and will not be able to access the UI of this feature
```suggestion
Disabling this feature hides the related Integrated Alerting user interface and stops any alert notifications.
```

2021-04-22 06:22 UTC, PaulJacobs-percona commented on docs/how-to/configure.md
> +If you'll disable the already enabled Telemetry feature PMM will stop sending data and all feature where you can get some data from Percona will be not available to be enabled
What features specifically are not available to the user when they disable telemetry? I have reworded an already vague sentence but it should be clearer.

2021-04-22 06:24 UTC, PaulJacobs-percona requested changes
These texts seem to be simply stating the negative of an already obvious thing. "When on, features works." You've added "When off, it doesn't." Is it really necessary?

2021-04-30 08:38 UTC, closed without merging