Backup and Restore: delete backup
percona/pmm-doc pull request #551
Opened 2021-07-14 11:33 UTC by fabio-silva

2021-07-15 12:06 UTC, PaulJacobs-percona requested changes

2021-07-15 13:49 UTC, fabio-silva commented on docs/using/backup.md
> +4. Check / uncheck "Delete from storage" - depending on this, your actual data might be erased.
Thanks @PaulJacobs-percona .
Yes, you got it right. I changed the phrasing a bit, do we think it's clearer now?

2021-07-16 08:28 UTC, PaulJacobs-percona commented on docs/using/backup.md
> +4. Check / uncheck "Delete from storage" - depending on this, your actual data might be erased.
Yes @fabio-silva, subtly but significantly improved, thanks!

2021-07-16 08:34 UTC, PaulJacobs-percona approved these changes

2021-07-16 08:35 UTC, merged