PMM-8079 Update operators
percona/pmm-doc pull request #552
Opened 2021-07-15 08:34 UTC by tiagomotasantos

Shows instructions on how to update an operator when a new version is available

2021-07-15 08:36 UTC, jprukner requested changes

2021-07-15 08:36 UTC, jprukner commented on docs/using/dbaas.md
> +When a new version of the operator is available the *Operators* column shows a message with this information. Cick the message to go to the operator release notes to find out more about the update.
Click

2021-07-15 08:37 UTC, tiagomotasantos commented on docs/using/dbaas.md
> +When a new version of the operator is available the *Operators* column shows a message with this information. Cick the message to go to the operator release notes to find out more about the update.
Thanks done!

2021-07-15 08:43 UTC, jprukner approved these changes
:+1:

2021-07-15 09:13 UTC, PaulJacobs-percona approved these changes
I'll share a preview in the main comments.

2021-07-15 09:14 UTC, PaulJacobs-percona commented
Preview https://60eff3b93ca8940008c5e743--pmm-doc.netlify.app/using/dbaas.html

2021-07-16 08:35 UTC, PaulJacobs-percona approved these changes

2021-07-16 08:36 UTC, merged