PMM-9144-MySQL-inventory-page-for-AWS-RDS-or-Aurora: update add insta…
percona/pmm-doc pull request #663
Opened 2021-12-16 11:46 UTC by solovevayaroslavna

https://github.com/percona-platform/grafana/pull/287
https://jira.percona.com/browse/PMM-9144

2021-12-17 07:38 UTC, rasika-chivate requested changes

2021-12-17 11:16 UTC, rasika-chivate commented on docs/setting-up/client/aws.md
>      !!! note alert alert-primary ""
Thanks for the reply @rnovikovP. 

The following statement holds true if we are considering MYSQL only, but we are trying to generalise and not stick to just MYSQL. So how valid is the following statement:

"If you have Amazon RDS with a MySQL version prior to 5.5, REPLICATION CLIENT privilege is not available there and has to be excluded from the above statement."

2021-12-17 11:18 UTC, rnovikovP commented on docs/setting-up/client/aws.md
>      !!! note alert alert-primary ""
I have no idea about specific 5.5 as it was EOLed a long time ago ...

2021-12-17 11:21 UTC, rasika-chivate commented on docs/setting-up/client/aws.md
>      !!! note alert alert-primary ""
In that case I think would it be a good idea to remove the following statement: Please reaffirm @rnovikovP 

"If you have Amazon RDS with a MySQL version prior to 5.5, REPLICATION CLIENT privilege is not available there and has to be excluded from the above statement."

2021-12-17 11:36 UTC, rnovikovP commented on docs/setting-up/client/aws.md
>      !!! note alert alert-primary ""
🤦‍♂️ . line 146 yes, it needs to be removed  (can't do this in UI   for some reasons  ( )

also, please remove  146-151  lines, all as they  are "not accurate" and not related to the context

2021-12-17 12:29 UTC, percona-csalguero approved these changes

2021-12-20 10:27 UTC, rnovikovP approved these changes

2021-12-20 12:41 UTC, rasika-chivate approved these changes

2021-12-20 12:45 UTC, merged

2021-12-20 20:45 UTC, rnovikovP commented
oops, this needs to go to the 2.26 branch as the `main` = "What we  have published on the website"  so  this  update  can be published any moment on the website, but the version this  change applicable not yet released

2021-12-22 10:43 UTC, percona-csalguero commented
> oops, this needs to go to the 2.26 branch as the `main` = "What we have published on the website" so this update can be published any moment on the website, but the version this change applicable not yet released

Should I revert it until next version?