Added changes for Test Email option
percona/pmm-doc pull request #668
Opened 2021-12-22 10:10 UTC by catalinaadam

Added description for Test Email Configuration and improved the current structure of the "Set up a communication channel" topic.

2021-12-22 10:21 UTC, rnovikovP commented
https://github.com/percona/pmm-doc/pull/668/commits/27dcaf7372691dbee75725126ff635f24f685238  
 LGTM
but I'm  🤔  about other commits. They need to be verified, as  they can add old text because of branch changes

2021-12-22 10:33 UTC, rasika-chivate approved these changes

2021-12-22 10:34 UTC, fabio-silva commented
> [27dcaf7](https://github.com/percona/pmm-doc/commit/27dcaf7372691dbee75725126ff635f24f685238) LGTM but I'm 🤔 about other commits. They need to be verified, as they can add old text because of branch changes

Yeah, this branch was based on main, we just changed that to 2.26.0, all good now 👍

2021-12-22 11:14 UTC, fabio-silva requested changes

2021-12-22 11:14 UTC, fabio-silva commented on docs/release-notes/2.26.0.md
> +# Percona Monitoring and Management 2.21.0
2.26.0 ?

2021-12-22 11:14 UTC, fabio-silva commented on docs/release-notes/2.26.0.md
> +      <td class="field-body">August 26, 2021</td>
should we change this date?

2021-12-22 19:02 UTC, fabio-silva approved these changes
🚀 🚀

2021-12-24 09:04 UTC, rnovikovP approved these changes

2021-12-30 12:04 UTC, merged