PMM-9312 Documentation for collstats and indexstats
percona/pmm-doc pull request #675
Opened 2022-01-04 15:35 UTC by percona-csalguero

2022-01-04 15:47 UTC, igroene approved these changes
LGTM

2022-01-05 05:08 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +## Advanced Options
Advanced Options:

The advanced options while setting up PMM to monitor MongoDB database instance are as follows.

2022-01-05 05:10 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +### Enabling all collectors
Avoid Gerunds:

### Enable all collectors

2022-01-05 05:12 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +To enable all collectors, add `--enable-all-collectors` to the `pmm-admin add mongodb` command.
To enable all the collectors pass the parameter add --enable-all-collectors in the pmm-admin add mongodb command.

2022-01-05 05:13 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +This will enable: `collstats`, `dbstats`, `indexstats` and the `topmetrics` collectors.
This will enable `collstats`, `dbstats`, `indexstats`, and `topmetrics` collectors.

2022-01-05 05:13 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +### Disable some collectors.
### Disable some collectors

2022-01-05 05:15 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +To enable some collectors but not all of them, it is posible to combine `--enable-all-collectors` along with `--disable-collectors`.
To enable some of the collectors, you can combine --enable-all-collectors and --disable-collectors.

2022-01-05 05:27 UTC, rasika-chivate requested changes
I am proposing some changes.

2022-01-05 05:27 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +For example, if you want all collectors but `topmetrics`, specify:
For example, if you want all collectors except topmetrics, specify:

2022-01-05 05:27 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +200 collections across all databases, excluding the collections in the system databases `admin`, `config`, `local`.
By default, all the collectors are enabled. However, collStats and indexStats are enabled if there are less than 200 collections across all the databases. This excludes the collections in the system databases admin, config, and local.

2022-01-05 05:27 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +The `--collector.collstats-limit` also accepts `-1` to indicate unlimited number of collections collStats and indexStats can handle.
The `--collector.collstats-limit` also accepts `-1` to indicate an unlimited number of collections collStats and indexStats can handle.

2022-01-05 05:27 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +It is also possible to enable collStats and indexStats only for some databases or collections.
Also, it is possible to enable collStats and indexStats only for some databases or collections.

2022-01-05 05:27 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +This parameter receives a comma separated list of namespaces in the form `database.collection`.
Using --stats-collections, you can specify the databases and collections from which collStats and indexStats will collect data. This parameter receives a comma-separated list of namespaces in the form database. collection.

2022-01-05 05:27 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +#### Usage example
#### Example

2022-01-05 05:27 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +## Advanced Options
## Advanced Options:

Add this sentence as we should not have orphan headings.

"The advanced options while setting up PMM to monitor MongoDB database instance are as follows."

2022-01-05 05:27 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +### Enabling all collectors
Avoid Gerunds:

### Enable all collectors

2022-01-05 05:27 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +To enable all collectors, add `--enable-all-collectors` to the `pmm-admin add mongodb` command.
To enable all the collectors pass the parameter add --enable-all-collectors in the pmm-admin add mongodb command.

2022-01-05 05:27 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +This will enable: `collstats`, `dbstats`, `indexstats` and the `topmetrics` collectors.
This will enable collstats, dbstats, indexstats, and topmetrics collectors.

2022-01-05 05:27 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +### Disable some collectors.
## Disable some collectors

2022-01-05 05:27 UTC, rasika-chivate commented on docs/setting-up/client/mongodb.md
> +To enable some collectors but not all of them, it is posible to combine `--enable-all-collectors` along with `--disable-collectors`.
To enable some of the collectors, you can combine --enable-all-collectors and --disable-collectors.

2022-01-05 09:33 UTC, rnovikovP commented
Until we make Collection statistics collected by default - there is no need to add them on the main Mongo DB  page. 
Even at that moment - all advanced options and most importantly, information about collectors  -  must go to the Reference manual section  https://www.percona.com/doc/percona-monitoring-and-management/2.x/details/commands/pmm-admin.html

2022-01-06 09:05 UTC, rnovikovP requested changes
Information here - too technical + not fully implemented,  so need to go to reference, not the primary documentation.

2022-01-06 19:25 UTC, rnovikovP approved these changes

2022-01-10 08:35 UTC, rasika-chivate requested changes
Please find my changes:

PMM starts the MongoDB exporter by default by using these parameters:

To enable all collectors, add the parameter --enable-all-collectors to the pmm-admin add mongodb command. 


This will enable collstats, dbstats, indexstats, and topmetrics collectors.

To enable some collectors, pass the  --enable-all-collectors parameter along with the --disable-collectors parameter.

**Enable dbStats, collStats and indexStats**

 All the collectors are enabled by default. However, collStats and indexStats are enabled if there are less than 200 collections across all the databases, excluding the admin, config, and local system databases.

For collstats and indexstats:

- The value of the parameter -collector.collstats-limit -1 indicates that collStats and indexStats can handle unlimited collections.

- You can enable collStats and indexStats only for some databases or collections.

- You can specify the databases and collections that collStats and indexStats will use to collect data using the parameter --stats-collections. This parameter receives a comma-separated list of namespaces in the form database. collection.


Example:

--stats-collections=db1,db2.col1

On db1 - It will run the collectors for all collections.

On db2 -  It will run the collectors only for collection col1.

2022-01-10 17:03 UTC, rasika-chivate reviewed
I have made some changes in the file.

2022-01-10 17:06 UTC, rasika-chivate commented
@rnovikovP I have made a few changes. Please reaffirm if they are fine.

2022-01-10 17:28 UTC, percona-csalguero commented
Closed in favor of https://github.com/percona/pmm-doc/pull/675

2022-01-10 17:28 UTC, closed without merging