added wget and highlight other mode
percona/pmm-doc pull request #687
Opened 2022-01-26 19:43 UTC by shoffman-percona

added instructions for using wget (curl not part of ubuntu default install)
Added information about interactive mode for users that want to customize installation parameters from our defaults

2022-01-26 20:32 UTC, rnovikovP commented
@shoffman-percona , @nikita-b  can  we have this  "one lined" into something like :
(curl -fsSL https://www.percona.com/get/pmm ||  wget -O - https://www.percona.com/get/pmm ) | /bin/bash  

? 
 so it executes the first or second command if the first is failed?

2022-01-26 20:35 UTC, shoffman-percona commented
> @shoffman-percona , @nikita-b can we have this "one lined" into something like : (curl -fsSL https://www.percona.com/get/pmm || wget -O - https://www.percona.com/get/pmm ) | /bin/bash
> 
> ? so it executes the first or second command if the first is failed?

We do that now in the script but the idea is to not have big wild lines of code for average "joe user" to have to parse...

2022-01-26 20:36 UTC, BupycHuk approved these changes

2022-01-26 21:28 UTC, nikita-b approved these changes

2022-01-27 12:01 UTC, rnovikovP commented
> average "joe user."

but now we are asking Joe to know what system he runs command .. does it Curl or Wget based  🤔

2022-01-27 14:44 UTC, denisok requested changes

2022-01-27 14:44 UTC, denisok commented on docs/setting-up/server/easy-install.md
> +curl -fsSL https://www.percona.com/get/pmm (or wget https://www.percona.com/get/pmm)
```suggestion
curl -fsSLO https://www.percona.com/get/pmm (or wget https://www.percona.com/get/pmm)
```

2022-01-27 14:44 UTC, denisok commented on docs/setting-up/server/easy-install.md
> +curl -fsSL https://www.percona.com/get/pmm (or wget https://www.percona.com/get/pmm)
without `O` it would be console.

2022-01-27 15:46 UTC, catalinaadam reviewed
Made a few suggestions to keep list items parallel.

2022-01-27 20:27 UTC, shoffman-percona commented on docs/setting-up/server/easy-install.md
>  - If a PMM Server Docker container is running, it is stopped and backed up.
Updated!

2022-01-27 20:27 UTC, shoffman-percona commented on docs/setting-up/server/easy-install.md
> +- this script also has an interactive mode if you'd like to change default settings:
Updated!

2022-01-27 21:52 UTC, denisok approved these changes

2022-02-04 12:43 UTC, rasika-chivate approved these changes

2022-02-04 15:18 UTC, merged