Reworded IA topic and Added info about Silencing All alerts
percona/pmm-doc pull request #715
Opened 2022-02-21 14:21 UTC by catalinaadam

Rewrote Integrated Alerting topic (PMM-8672) and added info about Silencing Alerts (PMM-9182)

2022-02-22 07:35 UTC, rasika-chivate requested changes

2022-02-22 10:30 UTC, fabio-silva requested changes

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +For example, to validate that a MongoDB instance is down, shut down a member of a three-node replica set, then check that the expression **{service_type="mongodb"}**  returns **0** in **Explore > Met
```suggestion
For example, to validate that a MongoDB instance is down, shut down a member of a three-node replica set, then check that the expression **{service_type="mongodb"}** returns **0** in **Explore > Metrics**.
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +3. In the **Add Alert** rule dialog, choose the template on which you want to base the new alert rule. This automatically populates the **Threshold**, **Duration**, **Severity** fields with informati
`Threshold` and/or others is a parameter coming from the template defined by the user, so we shouldn't talk about it here. The fields that show up are the params defined beforehand (but Duration and Severity are indeed always there).

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +    - To silence all Alerts, click Silence All at the top right side of the Alerts table.
We also have the option to "unsilence all", should we refer it here?

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +d Alerting is currently in [Technical Preview](../details/glossary.md#technical-preview). This means that this feature is still under development and is subject to change. Therefore, we recommend tha
```suggestion
Alerting is currently in [Technical Preview](../details/glossary.md#technical-preview). This means that this feature is still under development and is subject to change. Therefore, we recommend that early adopters use Integrated Alerting for testing purposes only.
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +    - For **Slack**, specify the Slack webhook URL to use. Currently, you can only configure one Slack channel for each Slack URL.
```suggestion
    - For **Slack**, specify the Slack Webhook URL to use. Currently, you can only configure one Slack channel for each Slack URL.
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +Alert templates contain general template details and an alert expression defined in [MetricsQ](https://docs.victoriametrics.com/MetricsQL.html). This query language is backward compatible with Promet
```suggestion
Alert templates contain general template details and an alert expression defined in [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html). This query language is backward compatible with Prometheus QL.
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +Alert templates contain general template details and an alert expression defined in [MetricsQ](https://docs.victoriametrics.com/MetricsQL.html). This query language is backward compatible with Promet
```suggestion
Alert templates contain general template details and an alert expression defined in [MetricsQ](https://docs.victoriametrics.com/MetricsQL.html). This query language is backward compatible with PromQL.
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +    - **type** (required): PMM currently supports the float type. string,  bool and another types will be available in a future release.
```suggestion
    - **type** (required): PMM currently supports the *float* type. *string*, *bool* and another types will be available in a future release.
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +    - **range** (optional): defines the boundaries for the value of a  float parameter
```suggestion
    - **range** (optional): defines the boundaries for the value of a float parameter
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +   - **value** (optional): default  parameter value. Value strings must not include any of these special characters: < > ! @ # $ % ^ & * ( ) _ / \ ' + - = (space)
```suggestion
   - **value** (optional): default parameter value. Value strings must not include any of these special characters: < > ! @ # $ % ^ & * ( ) _ / \ ' + - = (space).
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> + - **labels** (optional): are additional labels to be added to generated alerts
```suggestion
- **labels** (optional): are additional labels to be added to generated alerts.
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +- **severity** (required): specifies default alert severity level
```suggestion
- **severity** (required): specifies default alert severity level.
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +- **for** (required): specifies the duration of time that the expression must be met before the alert will be fired
```suggestion
- **for** (required): specifies the duration of time that the expression must be met before the alert will be fired.
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +If you want to create custom templates, you can test the MetricsQ expressions for your custom template in the **Explore** section of PMM. Here you can also query any PMM internal database.
```suggestion
If you want to create custom templates, you can test the MetricsQL expressions for your custom template in the **Explore** section of PMM. Here you can also query any PMM internal database.
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +For example, to validate that a MongoDB instance is down, shut down a member of a three-node replica set, then check that the expression **{service_type="mongodb"}**  returns **0** in **Explore > Met
```suggestion
For example, to validate that a MongoDB instance is down, shut down a member of a three-node replica set, then check that the expression **{service_type="mongodb"}** returns **0** in **Explore > Metrics**.
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +3. In the **Add Alert** rule dialog, choose the template on which you want to base the new alert rule. This automatically populates the **Threshold**, **Duration**, **Severity** fields with informati
Again, let's not talk about the threshold

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +Starting with PMM 2.26, alert rules are no longer dependent on their source rule template after creation. This means that you can update or delete rule templates without impacting existing rules that
```suggestion
Starting with PMM 2.26.0, alert rules are no longer dependent on their source rule template after creation. This means that you can update or delete rule templates without impacting existing rules that are based on that template.
```

2022-02-22 10:30 UTC, fabio-silva commented on docs/using/alerting.md
> +PMM 2.26 introduced major changes to the core structure of rule templates. As a result, alert rules and templates created in previous PMM versions are not compatible with PMM 2.26.0 and cannot be mig
Let's use 2.26.0 and 2.25.0 all over the place as well

2022-02-23 11:12 UTC, catalinaadam reviewed
Implemented suggested changes.

2022-02-23 11:19 UTC, merged