Updated index to show Develop Checks topic in the Help ToC
percona/pmm-doc pull request #719
Opened 2022-03-01 11:59 UTC by catalinaadam

2022-03-01 12:16 UTC, rasika-chivate commented
Please update the mkdocs-base.yml file as well.

2022-03-01 12:17 UTC, atymchuk commented on mkdocs-base.yml
> +        - details/develop-checks.md
I think we need to maintain consistency in indentation

2022-03-01 12:19 UTC, atymchuk requested changes

2022-03-01 12:19 UTC, atymchuk commented on mkdocs-base.yml
> +        - details/develop-checks.md
```suggestion
        - advisors/index.md 
```

2022-03-01 12:36 UTC, rasika-chivate approved these changes

2022-03-02 08:27 UTC, atymchuk commented on docs/details/advisors/index.md
> +## [How to develop security checks](./checks/develop-checks.md)
@catalinaadam I'm not really happy with how this one looks like, but couldn't come up with a good alternative. Maybe you can? :)

2022-03-04 09:18 UTC, atymchuk approved these changes

2022-03-07 11:35 UTC, merged