PMM-9670 using API key for authentication
percona/pmm-doc pull request #722
Opened 2022-03-04 11:06 UTC by rasika-chivate

Use API keys as a replacement for basic authentication.

2022-03-04 12:17 UTC, BupycHuk approved these changes

2022-03-04 12:22 UTC, nikita-b approved these changes

2022-03-04 12:35 UTC, puneet0191 approved these changes

2022-03-05 18:20 UTC, atymchuk requested changes

2022-03-05 18:20 UTC, atymchuk commented on docs/setting-up/server/index.md
> +1. Authenticating using API.
```suggestion
1. Authenticating using API keys.
```

2022-03-05 18:20 UTC, atymchuk commented on docs/setting-up/server/index.md
> +1. Authenticating using API.
This will make it consistent with the rest of the narrative.

2022-03-07 07:53 UTC, atymchuk approved these changes

2022-03-07 08:32 UTC, merged