PMM-9590 credentials source flag
percona/pmm-doc pull request #799
Opened 2022-05-19 11:34 UTC by rasika-chivate

Added credentials-source flag which can be used instead of username and password flags.

2022-05-19 12:28 UTC, denisok approved these changes

2022-05-19 15:50 UTC, rnovikovP requested changes
This now looks like Auth command for `pmm-admin` in general. 

But in reality, this is part of `add` command.
I think this needs to be moved to   Database commands  section 

![image](https://user-images.githubusercontent.com/25495422/169342144-2895b243-88df-479d-b0d7-f7bdcddd4b1b.png)

2022-05-20 07:24 UTC, beatahandzelova approved these changes

2022-05-20 07:36 UTC, beatahandzelova approved these changes

2022-05-20 21:53 UTC, rnovikovP approved these changes

2022-05-23 06:09 UTC, merged