Advisors filtering
percona/pmm-doc pull request #820
Opened 2022-07-05 17:31 UTC by catalinaadam

2022-07-11 10:10 UTC, fabio-silva requested changes

2022-07-11 10:10 UTC, fabio-silva commented on docs/how-to/advisors.md
> +3. Scroll though the list to find a specific check, or use the **Filter** section to search by Name, Description, Status or Interval.
```suggestion
3. Scroll through the list to find a specific check, or use the **Filter** section to search by Name, Description, Status or Interval. 
```

2022-07-11 10:10 UTC, fabio-silva commented on docs/how-to/advisors.md
> +    If you need to share filtered alert results with your team members, send them the PMM URL. This saves your search criteria and results.
I think you mean checks, not alerts

2022-07-12 13:46 UTC, fabio-silva approved these changes

2022-07-14 10:10 UTC, rasika-chivate commented on docs/how-to/advisors.md
> +3. Scroll through the list to find a specific check, or use the **Filter** section to search by Name, Description, Status or Interval.
```suggestion
3. Scroll through the list to find a specific check, or use the **Filter** section to search by Name, Description, Status, or Interval. 
```

2022-07-18 08:16 UTC, merged