changes for PMM-8455
percona/pmm-doc pull request #823
Opened 2022-07-06 19:41 UTC by catalinaadam

2022-07-12 13:47 UTC, fabio-silva approved these changes

2022-07-12 15:31 UTC, fabio-silva approved these changes

2022-07-14 09:57 UTC, rasika-chivate requested changes

2022-07-14 09:57 UTC, rasika-chivate commented on docs/details/develop-checks/checks-v2.md
> +PMM groups failed checks by their severity, and displays them under **Advisors Checks > Failed Checks**.
```suggestion
PMM groups the failed checks by severity and displays them under **Advisors Checks > Failed Checks**. 
```

2022-07-14 09:57 UTC, rasika-chivate commented on docs/details/develop-checks/index.md
>  PMM 2.28 upgraded Advisor checks to version 2, to accomodate the following major enhancements introduced in this release:
```suggestion
PMM 2.28 upgraded Advisor checks to version 2 to accommodate the following significant enhancements introduced in this release: 
```

2022-07-18 08:12 UTC, merged