Resolving Issues section improvements
percona/pmm-doc pull request #866
Opened 2022-09-13 02:29 UTC by rasika-chivate

Improving the resolving issues section.

2022-09-14 08:13 UTC, dygksy requested changes
May I ask for a screenshot for "PMM server not updating correctly" part?
And please also ask Michael for review.

2022-09-19 10:04 UTC, rasika-chivate commented
> May I ask for a screenshot for "PMM server not updating correctly" part? And please also ask Michael for review.

We do not give screenshots for troubleshooting section, And going forward we are planning to remove screenshots from the doc. We can have a discussin with Alex about this.

2022-09-19 10:08 UTC, dygksy approved these changes

2022-09-19 11:38 UTC, michal-kralik approved these changes

2022-09-26 13:06 UTC, merged