PMM-11159 Doc changes for new MySQL explain method.
percona/pmm-doc pull request #936
Opened 2022-12-05 09:43 UTC by JiriCtvrtka

https://jira.percona.com/browse/PMM-11159

2022-12-05 13:56 UTC, rasika-chivate requested changes

2022-12-05 13:56 UTC, rasika-chivate commented on docs/using/query-analytics.md
> +Since PMM version 2.33 is `explain` supported even without `examples` for MySQL now. If query to explain contains sensitive data they will be replaced by placeholders.
```suggestion
Starting with PMM 2.33.0, for MySQL, the *Explain* tab is supported without the *Examples* tab. If a query in the *Explain* tab contains sensitive data, placeholders will replace them.
```

2022-12-05 13:56 UTC, rasika-chivate commented on docs/using/query-analytics.md
> +You should provide values for these placeholders before you can run `explain`. Please check attached above below.
```suggestion
You have to specify the values for these placeholders before you can run *Explain*, as shown in the image below.
```

2022-12-05 13:56 UTC, rasika-chivate commented on docs/using/query-analytics.md
> +Query in the picture has 5 placeholders. So thats why you should fulfill 5 input fields with correct values. Once you have fulfilled these values you can click on `explain`
```suggestion
The image shows a query with five placeholders. Therefore, you must enter the correct values in all five fields. After filling in these values, click *Explain* to get the results like in the previous PMM versions without data leaks.
```

2022-12-13 09:23 UTC, JiriCtvrtka commented on docs/using/query-analytics.md
> +and you will get result like in previous PMM versions. This method of `explain` prevents data leak.
```suggestion
You will get result like in previous PMM versions. This method of `explain` prevents data leak.
```

2022-12-13 09:36 UTC, merged