PMM-8164 Update information about caching on client side
percona/pmm-doc pull request #938
Opened 2022-12-07 10:44 UTC by BupycHuk

2022-12-07 15:25 UTC, denisok approved these changes

2022-12-30 09:13 UTC, rasika-chivate requested changes

2022-12-30 09:13 UTC, rasika-chivate commented on docs/setting-up/client/index.md
> +    - Disk -- A minimum of 100 MB of storage is required for installing the PMM Client package. With a good connection to PMM Server, additional storage is not required. However, the client needs to
```suggestion
    - Disk -- A minimum of 100 MB of storage is required for installing the PMM Client package. With a good connection to PMM Server, additional storage is not required. However, the client needs to store any collected data that it cannot dispatch immediately, so additional storage may be required if the connection is unstable or the throughput is low. VMagent uses 1 GB of disk space for cache during a network outage. QAN, on the other hand, uses RAM to store cache.
```

2023-01-13 15:34 UTC, rasika-chivate approved these changes

2023-01-13 15:34 UTC, merged