PMM-11000 Doc PMM Pacemaker EC2
percona/pmm-doc pull request #942
Opened 2022-12-13 08:54 UTC by anton-bystrov

PMM-11000 Documentation how to install HA PMM instance via Pacemaker on EC2 AWS.

2022-12-19 14:53 UTC, atymchuk requested changes

2022-12-19 14:53 UTC, atymchuk commented on docs/how-to/pmm-ec2.md
> +- Allowed incoming/ougoing data in security groups for xpecific ports [Pacemaker](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/high_availability_add-on_reference/s1-f
```suggestion
- Allow ingress/egress on specific ports in security groups [Pacemaker](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/high_availability_add-on_reference/s1-firewalls-haar) and [PMM](https://docs.percona.com/percona-monitoring-and-management/setting-up/server/network.html), [Glusterfs](https://docs.gluster.org/en/latest/Administrator-Guide/Setting-Up-Clients/).
```

2022-12-19 14:53 UTC, atymchuk commented on docs/how-to/pmm-ec2.md
> +This instructions should be done on both nodes.
```suggestion
Steps outlines in this instruction should be performed on both nodes.
```

2022-12-19 14:53 UTC, atymchuk commented on docs/how-to/pmm-ec2.md
> +The next define AWS credentials:
```suggestion
Next, define AWS credentials:
```

2022-12-19 14:53 UTC, atymchuk commented on docs/how-to/pmm-ec2.md
> +The first install AWS CLI full instruction available [here](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html).
Too vague of a sentence, not clear what the user should do.

2023-05-16 15:21 UTC, rnovikovP commented
Lovely and exciting content, but we can't put it in the official documentation for now. Let's start with the blog post, see how many people are interested, and then, if needed, find a way to improve UX to do such deploy.

2024-12-20 10:18 UTC, ademidoff commented
Closing as stale.

2024-12-20 10:18 UTC, closed without merging