PMM-11031 advanced-settings-UI
percona/pmm-doc pull request #958
Opened 2023-01-18 10:03 UTC by rasika-chivate

2023-01-23 09:49 UTC, beatahandzelova commented on docs/get-started/dbaas.md
> +    1. Select the number of nodes. (The lower limit is 3.)
We can create single node too. Limit is 1.

2023-01-23 09:50 UTC, beatahandzelova commented on docs/get-started/dbaas.md
> +    - *Internet Facing* - Select this checkbox if you want the cluster to be accessible on the internet.
Internet with capital "I".

2023-01-23 09:51 UTC, beatahandzelova commented
@rasika-chivate there's a bug visible in these new screenshots https://jira.percona.com/browse/PMM-11369. Can you replace them so we don't see the $ sign please?

2023-01-24 12:45 UTC, gen1us2k approved these changes

2023-01-24 12:50 UTC, denisok requested changes
@solovevayaroslavna this screenshot for the statuses needs to be updated:
https://github.com/percona/pmm-doc/pull/958/files#diff-28552b691583f7b3f6d9e1db1e59975df317924b6ab9e43fc72782a18857466bR127
`../_images/PMM_DBaaS_Kubernetes_Cluster_Operator_Status.png`

@rasika-chivate Use helm list is broken:
https://github.com/percona/pmm-doc/pull/958/files#diff-28552b691583f7b3f6d9e1db1e59975df317924b6ab9e43fc72782a18857466bR35
in `## Add a Kubernetes cluster automatically` list starts with 1 and continuous with 1.

2023-01-30 10:31 UTC, denisok approved these changes

2023-01-30 13:53 UTC, merged