PMM-11445 edit page missing
percona/pmm-doc pull request #962
Opened 2023-01-25 07:03 UTC by rasika-chivate

Edit page missing on PMM docs

2023-01-25 07:43 UTC, LenzGr commented
@rasika-chivate please consider adding some background info to the git commit message about this change, and why it is necessary. I added the following to mine:
```

Material Theme for MkDocs version 9.x changed the default behavior of the
"Edit this page" functionality. Now both editing and viewing the source code
must be explicitly enabled:

https://squidfunk.github.io/mkdocs-material/upgrade/#upgrading-from-8x-to-9x
```

2023-01-26 14:58 UTC, atymchuk commented
@rasika-chivate @LenzGr Why don't we pin the MaterialUI version so we 1) upgrade when necessary and 2) don't face surprises like this.

2023-01-26 14:58 UTC, atymchuk approved these changes

2023-01-26 15:00 UTC, atymchuk requested changes

2023-01-26 15:00 UTC, atymchuk commented on mkdocs.yml
> +features:
I believe this changes belongs in mkdocs-base.yml, since it is extended by multiple yml files.

2023-01-27 12:08 UTC, atymchuk approved these changes

2023-03-03 14:50 UTC, LenzGr commented
@rasika-chivate seems like the edit icons re-appeared on the PMM docs, even though this PR hasn't been merged. Could you please take a look?

2023-03-15 08:55 UTC, rasika-chivate commented
Modified the docs with the PR: https://github.com/percona/pmm-doc/pull/972

2023-03-15 08:55 UTC, closed without merging